default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  url: <%= DatabaseUrl.development %>

test:
  <<: *default
  url: <%= DatabaseUrl.test %>

production:
  <<: *default
  url: <%= DatabaseUrl.production %>
