name: build
on: [push, pull_request]

jobs:
  test:
    name: Build & Test
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test
      RACK_ENV: test
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: acme
          POSTGRES_PASSWORD: acme
          POSTGRES_DB: acme
        ports:
          - "5432:5432"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Install dependencies
        run: |
          bundle config set path vendor/bundle
          bundle config set without development
          bundle install --jobs 4 --retry 3
          yarn install
      - name: Run tasks
        run: |
          bundle exec rails static_analysis:all
      - name: Set up database
        run: bin/rails db:test:prepare
      - name: Run tests
        run: bin/rails test
